[package]
name = "cairo_loto_poc"
version = "0.1.0"
edition = "2023_01"


[dependencies]
starknet = "2.6.3"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.12.0" }


[[target.starknet-contract]]
sierra = true


# below is required to use ArgentX browser extension to declare&deploy contracts on mainnet
# (also needed if using sn foundry forge/cast)
casm=true


# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
